# Generated by Django 4.2.8 on 2023-12-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_checklistdetails_time'),
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='station_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
