# Generated by Django 4.2.8 on 2023-12-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_checklistdetails_time'),
        ('accounts', '0005_customuser_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
