# Generated by Django 4.2.8 on 2024-02-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0080_alter_checklistdetails_time_and_more'),
        ('accounts', '0010_alter_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
