# Generated by Django 4.2.8 on 2024-02-17 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Dept_Head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
