# Generated by Django 4.2.8 on 2024-02-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
    ]
