# Generated by Django 4.2.8 on 2024-06-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dept_Head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
