"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@4pquge9m(va7au#ws-7pg89r7l7drmxs#_ptn)^%xjerx*eac'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','127.0.0.1','192.168.1.160','localhost']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'user_management',
    'crispy_bootstrap4',
    'polls',
    'pettycash',
    'import_export',
    'itassets',
    'chartjs',
    'formtools',
    'django_select2',
    'simple_history',
    'quality',
    'django_redis',
    'channels',
     'news',
    'dynamic_breadcrumbs',
    'websockets',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
     'corsheaders',
    # 'compressor',
    
  
   
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myproject.custommiddleware.CustomUserMiddleware',
     
]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'


CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Riyadh'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}



ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myproject.context_processors.custom_context',
                'dynamic_breadcrumbs.context_processors.breadcrumbs',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sats',
        'USER': 'mysqluser',
        'PASSWORD': 'password',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')not working with nginx
STATIC_ROOT = '/var/www/static/'
STATICFILES_DIRS = [BASE_DIR / 'staticfiles',]

#COMPRESS_STORAGE_ALIAS = 'compressor.storage.CompressorFileStorage'
#COMPRESS_ROOT = '/var/www/static/'
#COMPRESS_ENABLED = True
#STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

MEDIA_URL = '/media/'

MEDIA_ROOT = '/var/www/media/'
#MEDIA_ROOT = '/media/windowsshare/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'


AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_URL = 'accounts:login'
LOGOUT_REDIRECT_URL = "/login"

SESSION_COOKIE_AGE = 1800
# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Using SMTP as the email backend

# SMTP Configuration (Replace these settings with your SMTP server details)
EMAIL_HOST = 'smtp.office365.com'  # SMTP server address
EMAIL_PORT = 587  # SMTP port (587 is commonly used for TLS)
EMAIL_HOST_USER = 'noreply@sats.com.sa'  # Your email address
#EMAIL_HOST_PASSWORD = 'brpdjxkvqytsdmdd'  # Your email password or app-specific password
EMAIL_HOST_PASSWORD = 'wbskdrfddjfvpdyq'  # Your email password or app-specific password

EMAIL_USE_TLS = True  # True if you're using TLS for encryption, False for plaintext

# Default email settings
DEFAULT_FROM_EMAIL = 'ajmal.ummer@sats.com.sa'  # Default sender email address
#PASSWORD_RESET_EMAIL_TEMPLATE = 'registration/password_reset_email.html'


TWILIO_ACCOUNT_SID = 'ACbbeec60b459735042a2d262be8581503'
TWILIO_AUTH_TOKEN = 'f49d5a588f45e5a5529bc5d36cd16b53'
TWILIO_WHATSAPP_NUMBER = '+15166898553'


####################for DRF token
""" REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
} """

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Enforce authentication globally
    ],
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access token expiration
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Refresh token expiration
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # If refresh tokens are rotated, blacklist the old ones
}





# Allow all origins (for development only)
CORS_ALLOW_ALL_ORIGINS = True