# Generated by Django 4.2.8 on 2023-12-12 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100)),
                ('checklistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.checklistdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.subjectspecificquestion')),
            ],
        ),
        migrations.CreateModel(
            name='GenQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100)),
                ('checklistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.checklistdetails')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.generalquestion')),
            ],
        ),
    ]
