# Generated by Django 4.2.8 on 2023-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_checklistdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='11:59:42'),
        ),
    ]
