# Generated by Django 4.2.8 on 2023-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_checklistdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Brand',
            field=models.CharField(default='DOOSAN', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Capacity',
            field=models.CharField(default='3TON', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Manufacture_Year',
            field=models.CharField(default=2016, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Serial_Number',
            field=models.CharField(default=123, max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='09:00:52'),
        ),
    ]
