# Generated by Django 4.2.8 on 2023-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_subject_brand_subject_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:09:00'),
        ),
    ]
