# Generated by Django 4.2.8 on 2023-12-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_station_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='station_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:29:00'),
        ),
    ]
