# Generated by Django 4.2.8 on 2023-12-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_subject_station_name_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:12:16'),
        ),
    ]
