# Generated by Django 4.2.8 on 2023-12-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='18:56:06'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
