# Generated by Django 4.2.8 on 2023-12-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_fuel_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='08:11:15'),
        ),
    ]
