# Generated by Django 4.2.8 on 2023-12-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_subject_fueltype_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectspecificquestion',
            name='fueltype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.fuel'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='10:18:33'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fueltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.fuel'),
        ),
    ]
