# Generated by Django 4.2.8 on 2023-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_subjectspecificquestion_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='20:29:47'),
        ),
        migrations.AlterField(
            model_name='subjectspecificquestion',
            name='text',
            field=models.TextField(verbose_name='Enter New question'),
        ),
    ]
