# Generated by Django 4.2.8 on 2023-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:50:04'),
        ),
    ]
