# Generated by Django 4.2.8 on 2024-01-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_checklistdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:18:31'),
        ),
    ]
