# Generated by Django 4.2.8 on 2024-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_checklistdetails_time_workpermit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='16:36:21'),
        ),
        migrations.DeleteModel(
            name='Workpermit',
        ),
    ]
