# Generated by Django 4.2.8 on 2024-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_checklistdetails_time_workpermit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:03:52'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='12:03:52'),
        ),
    ]
