# Generated by Django 4.2.8 on 2024-02-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0093_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='18:07:55'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='18:07:55'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Serial_Number', models.CharField(default=123, max_length=100)),
                ('Capacity', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Manufacture_Year', models.CharField(default=2016, max_length=100)),
                ('fueltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.fuel')),
                ('station_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.station')),
            ],
        ),
    ]
