# Generated by Django 4.2.8 on 2024-02-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_station_name'),
        ('polls', '0094_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='20:27:47'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='20:27:47'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
