# Generated by Django 4.2.8 on 2024-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0104_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:08:06'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:08:06'),
        ),
    ]
