# Generated by Django 4.2.8 on 2024-03-02 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0140_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='upload_Iqama',
            field=models.FileField(blank=True, null=True, upload_to='WorkPermit_iqama/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:17:46'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='14:17:46'),
        ),
    ]
