# Generated by Django 4.2.8 on 2024-04-04 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0142_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_Date', models.DateField()),
                ('Mode', models.IntegerField(choices=[(0, 'Entry'), (1, 'Exit')], default=1)),
                ('Return_status', models.CharField(max_length=5)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Driver_name', models.CharField(max_length=100)),
                ('Iqama_Number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Vehicle_Plate_Number', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:43:45'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='14:43:45'),
        ),
    ]
