# Generated by Django 4.2.8 on 2024-04-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0143_gatepass_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='Reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:54:17'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='14:54:17'),
        ),
        migrations.CreateModel(
            name='Gatepass_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=256)),
                ('qty', models.IntegerField()),
                ('Remarks', models.TextField()),
                ('GatePass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gatepass')),
            ],
        ),
    ]
