# Generated by Django 4.2.8 on 2024-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0144_gatepass_reason_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gatepass_Items',
            new_name='Gatepass_Items_Model',
        ),
        migrations.RenameModel(
            old_name='GatePass',
            new_name='GatePassModel',
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='15:05:58'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='15:05:58'),
        ),
    ]
