# Generated by Django 4.2.8 on 2024-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0146_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassmodel',
            name='Item_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='19:48:29'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='19:48:29'),
        ),
    ]
