# Generated by Django 4.2.8 on 2024-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0147_gatepassmodel_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='19:49:37'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Item_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='19:49:37'),
        ),
    ]
