# Generated by Django 4.2.8 on 2024-04-04 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0150_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassmodel',
            name='Contact_Details',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='19:58:53'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='19:58:53'),
        ),
    ]
