# Generated by Django 4.2.8 on 2024-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0153_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:03:54'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Vehicle_Plate_Number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:03:54'),
        ),
    ]
