# Generated by Django 4.2.8 on 2024-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0154_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:07:43'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Contact_Details',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Iqama_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:07:43'),
        ),
    ]
