# Generated by Django 4.2.8 on 2024-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0157_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:54:17'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Contact_Details',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Iqama_Number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:54:17'),
        ),
    ]
