# Generated by Django 4.2.8 on 2024-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0161_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gatepass/'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='16:01:55'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='16:01:55'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='16:01:55'),
        ),
    ]
