# Generated by Django 4.2.8 on 2024-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0163_gatepassmodel_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:24:30'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='13:24:30'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:24:30'),
        ),
    ]
