# Generated by Django 4.2.8 on 2024-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0164_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='13:25:58'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='13:25:58'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='13:25:58'),
        ),
    ]
