# Generated by Django 4.2.8 on 2024-04-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0168_contractor_workers_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='Contracting_Company_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.contractor'),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='workers',
            field=models.ManyToManyField(to='polls.workers'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='15:43:01'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='15:43:01'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='15:43:01'),
        ),
    ]
