# Generated by Django 4.2.8 on 2024-04-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0171_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='23:38:10'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='23:38:10'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Contracting_Company_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.contractor'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='23:38:10'),
        ),
    ]
