# Generated by Django 4.2.8 on 2024-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0174_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='23:56:08'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='23:56:08'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='23:56:08'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Iqama_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
