# Generated by Django 4.2.8 on 2024-04-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0175_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='10:12:40'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default='10:12:40'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default='10:12:40'),
        ),
    ]
