# Generated by Django 4.2.8 on 2024-04-24 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0179_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='15:36:45'),
        ),
        migrations.AlterField(
            model_name='gatepassmodel',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 12, 36, 45, 895249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 24, 12, 36, 45, 893875, tzinfo=datetime.timezone.utc)),
        ),
    ]
