# Generated by Django 4.2.8 on 2024-06-03 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0213_correctivemaintenance_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workpermits', to='polls.workorder'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='14:54:03'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 3, 11, 54, 3, 37114, tzinfo=datetime.timezone.utc)),
        ),
    ]
