# Generated by Django 4.2.8 on 2024-06-03 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0214_workpermit_work_order_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_contract',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='16:48:44'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 3, 13, 48, 44, 723858, tzinfo=datetime.timezone.utc)),
        ),
    ]
