# Generated by Django 4.2.8 on 2024-06-03 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0216_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='16:57:58'),
        ),
        migrations.AlterField(
            model_name='fa_contract',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Monthly'), (2, 'Quarterly'), (3, 'Every 2 months'), (4, 'Every 3 months'), (4, 'Every 4 months')], null=True),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 3, 13, 57, 58, 114210, tzinfo=datetime.timezone.utc)),
        ),
    ]
