# Generated by Django 4.2.8 on 2024-06-08 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_employee_id'),
        ('polls', '0222_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_contract',
            name='Department',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fa_Department', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:09:36'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 8, 9, 9, 36, 794880, tzinfo=datetime.timezone.utc)),
        ),
    ]
