# Generated by Django 4.2.8 on 2024-06-08 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_department_dept_head'),
        ('polls', '0223_fa_contract_department_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:12:43'),
        ),
        migrations.AlterField(
            model_name='fa_contract',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fa_Department', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 8, 9, 12, 43, 599560, tzinfo=datetime.timezone.utc)),
        ),
    ]
