# Generated by Django 4.2.8 on 2024-06-08 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0226_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:18:24'),
        ),
        migrations.AlterField(
            model_name='fa_contract',
            name='frequency',
            field=models.IntegerField(choices=[(1, '30 days'), (2, '90 days'), (3, '60 days'), (4, '120 days'), (5, '15 days')], null=True),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 8, 9, 18, 24, 863159, tzinfo=datetime.timezone.utc)),
        ),
    ]
