# Generated by Django 4.2.8 on 2024-07-06 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0231_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='next_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='11:34:54'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 6, 8, 34, 54, 293238, tzinfo=datetime.timezone.utc)),
        ),
    ]
