# Generated by Django 4.2.8 on 2024-09-15 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0232_preventivemaintenance_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='09:23:47'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 15, 6, 23, 47, 383602, tzinfo=datetime.timezone.utc)),
        ),
    ]
