# Generated by Django 4.2.8 on 2024-09-16 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0235_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_contract',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='21:26:50'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 16, 18, 26, 50, 977206, tzinfo=datetime.timezone.utc)),
        ),
    ]
