# Generated by Django 4.2.8 on 2024-09-18 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_alter_department_dept_head'),
        ('polls', '0237_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='22:12:26'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 18, 19, 12, 26, 785321, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='NewMaintanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.CharField(max_length=256, null=True)),
                ('purchase_order', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('uploaded_at', models.DateField(default=django.utils.timezone.now)),
                ('cm_datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fa_New_category', to='polls.fa_category')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.fa_contract')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fa_New_contractor', to='polls.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.station')),
                ('subcategory', models.ManyToManyField(blank=True, to='polls.fa_subcategory')),
                ('work_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newmaintenance', to='polls.workorder')),
            ],
        ),
    ]
