# Generated by Django 4.2.8 on 2024-09-19 09:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0238_alter_checklistdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdetails',
            name='time',
            field=models.TimeField(default='12:50:45'),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 19, 9, 50, 45, 436492, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='New_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('New_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='New_comments', to='polls.newmaintanence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fa_New_ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='contracts/Newattachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('filename', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fa_New_ContractFile', to='polls.newmaintanence')),
            ],
        ),
    ]
