# Generated by Django 4.2.8 on 2024-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_in_incidents_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInvolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iqama_id', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeesinvolved',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeesinvolved',
            name='gaca_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeesinvolved',
            name='iqama_id',
            field=models.DecimalField(decimal_places=0, default=2425924541, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeesinvolved',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeesinvolved',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='in_incidents',
            name='employees',
            field=models.ManyToManyField(related_name='incidents', to='quality.driverinvolved'),
        ),
    ]
