# Generated by Django 4.2.8 on 2024-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_driverinvolved_employeesinvolved_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_incidents',
            old_name='employees',
            new_name='driver_name',
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='employees_name',
            field=models.ManyToManyField(related_name='incidents', to='quality.employeesinvolved'),
        ),
    ]
