# Generated by Django 4.2.8 on 2024-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_rename_employees_in_incidents_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_incidents',
            name='bodyparts_affected',
            field=models.ManyToManyField(to='quality.in_bodyparts'),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='nature_of_injury',
            field=models.ManyToManyField(to='quality.in_natureofinjury'),
        ),
    ]
