# Generated by Django 4.2.8 on 2024-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_in_incidents_bodyparts_affected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_incidents',
            name='Summary',
            field=models.CharField(default='test incident', max_length=256),
        ),
    ]
