# Generated by Django 4.2.8 on 2024-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_in_incidents_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_incidents',
            name='contributory_factors',
            field=models.CharField(default='test incident', max_length=256),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='corrective_measurments',
            field=models.CharField(default='test incident', max_length=256),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='safety_images/'),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='safety_images/'),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='safety_images/'),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='safety_images/'),
        ),
        migrations.AddField(
            model_name='in_incidents',
            name='preventive_measures',
            field=models.CharField(default='test incident', max_length=256),
        ),
    ]
