# Generated by Django 4.2.8 on 2024-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_in_incidents_contributory_factors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_incidents',
            name='Summary',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='in_incidents',
            name='contributory_factors',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='in_incidents',
            name='corrective_measurments',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='in_incidents',
            name='preventive_measures',
            field=models.CharField(max_length=256),
        ),
    ]
