# Generated by Django 4.2.8 on 2024-02-25 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_alter_in_incidents_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_incidents',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
