# Generated by Django 4.2.8 on 2024-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_in_incidents_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinvolved',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='safety_images/'),
        ),
    ]
