# Generated by Django 4.2.8 on 2024-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_employeesinvolved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinvolved',
            name='upload_Iqama',
            field=models.FileField(blank=True, null=True, upload_to='safety_images/'),
        ),
    ]
