# Generated by Django 4.2.8 on 2024-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0015_employeesinvolved_upload_iqama'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinvolved',
            name='driver_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='incidents_driver', to='quality.driverinvolved'),
        ),
    ]
