# Generated by Django 4.2.8 on 2024-06-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0002_chatgroup_groupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
