# Generated by Django 4.2.8 on 2024-06-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0003_remove_groupmessage_author_remove_groupmessage_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
