# Generated by Django 4.2.8 on 2024-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
