# Generated by Django 4.2.8 on 2024-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(),
        ),
    ]
