# Generated by Django 4.2.8 on 2024-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0007_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='counter_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
