# Generated by Django 4.2.8 on 2024-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0008_ticket_called_ticket_counter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
    ]
