# Generated by Django 4.2.8 on 2024-06-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0009_ticket_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
