# Generated by Django 4.2.8 on 2024-07-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0011_counter_web_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Web_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
