# Generated by Django 4.2.8 on 2024-01-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='Asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
