# Generated by Django 4.2.8 on 2024-01-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0002_it_prodcuts_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
