# Generated by Django 4.2.8 on 2024-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0003_alter_it_prodcuts_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
