# Generated by Django 4.2.8 on 2024-01-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0004_alter_it_prodcuts_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='it_prodcuts',
            name='allocation_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='itassets.allocation_status'),
        ),
    ]
