# Generated by Django 4.2.8 on 2024-01-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_alter_checklistdetails_time_and_more'),
        ('itassets', '0005_allocation_status_it_prodcuts_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='station_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
