# Generated by Django 4.2.8 on 2024-01-11 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0006_it_prodcuts_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
