# Generated by Django 4.2.8 on 2024-01-28 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0007_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
