# Generated by Django 4.2.8 on 2024-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0008_it_prodcuts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
