# Generated by Django 4.2.8 on 2024-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0009_alter_it_prodcuts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='image',
            field=models.ImageField(blank=True, default='user_images/truck.png', null=True, upload_to='user_images/'),
        ),
    ]
