# Generated by Django 4.2.8 on 2024-02-01 10:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itassets', '0010_it_prodcuts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.CreateModel(
            name='ItAssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(default=datetime.date.today)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itassets.it_prodcuts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
