# Generated by Django 4.2.8 on 2024-02-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0011_alter_it_prodcuts_file_itassetallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itassetallocation',
            name='deallocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
