# Generated by Django 4.2.8 on 2024-02-03 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0012_itassetallocation_deallocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itassetallocation',
            name='allocation_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
