# Generated by Django 4.2.8 on 2024-02-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0013_alter_itassetallocation_allocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='current_allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_product', to='itassets.itassetallocation'),
        ),
    ]
