# Generated by Django 4.2.8 on 2024-02-03 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0015_alter_itassetallocation_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itassetallocation',
            name='allocation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 13, 54, 0, 234486, tzinfo=datetime.timezone.utc)),
        ),
    ]
