# Generated by Django 4.2.8 on 2024-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0016_alter_itassetallocation_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itassetallocation',
            name='allocation_date',
            field=models.DateTimeField(),
        ),
    ]
