# Generated by Django 4.2.8 on 2024-02-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_station_name'),
        ('itassets', '0018_alter_it_prodcuts_allocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='station_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
    ]
