# Generated by Django 4.2.8 on 2024-02-19 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0020_alter_it_prodcuts_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(verbose_name=datetime.date(2024, 2, 19)),
        ),
    ]
