# Generated by Django 4.2.8 on 2024-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0021_alter_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
