# Generated by Django 4.2.8 on 2024-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0023_alter_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='asset_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
