# Generated by Django 4.2.8 on 2024-02-20 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0026_customhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalit_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
    ]
