# Generated by Django 4.2.8 on 2024-02-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0027_natureofinjury_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NatureOfInjury',
        ),
    ]
