# Generated by Django 4.2.8 on 2024-02-21 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0028_delete_natureofinjury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalit_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
    ]
