# Generated by Django 4.2.8 on 2024-02-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0029_alter_historicalit_prodcuts_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalIt_Prodcuts',
        ),
    ]
