# Generated by Django 4.2.8 on 2024-02-23 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0030_delete_historicalit_prodcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
    ]
