# Generated by Django 4.2.8 on 2024-05-01 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0045_alter_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_prodcuts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='allocation_status',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='itassets.allocation_status'),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 1)),
        ),
    ]
