# Generated by Django 4.2.8 on 2024-05-11 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0047_alter_it_prodcuts_created_date_it_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_prodcuts',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itassets.it_model'),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
    ]
