# Generated by Django 4.2.8 on 2024-05-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0049_alter_it_prodcuts_created_date_it_mobile_cctv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_mobile',
            name='Itproduct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_phone', to='itassets.it_prodcuts'),
        ),
    ]
