# Generated by Django 4.2.8 on 2024-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0050_alter_it_mobile_itproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
