# Generated by Django 4.2.8 on 2024-05-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0051_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_under_warranty', models.BooleanField(default=False)),
                ('warranty_coverage', models.CharField(blank=True, max_length=100, null=True)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='itassets.it_prodcuts')),
                ('it_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='itassets.it_prodcuts')),
            ],
        ),
    ]
