# Generated by Django 4.2.8 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0053_maintenancerequest_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='warranty_coverage',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='Warranty_type',
            field=models.CharField(blank=True, choices=[('1', 'Full'), ('2', 'Partial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Payment_Mode',
            field=models.CharField(choices=[('1', 'PO'), ('2', 'Cash')], default='2', max_length=20),
        ),
    ]
