# Generated by Django 4.2.8 on 2024-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0055_alter_maintenancerequest_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
