# Generated by Django 4.2.8 on 2024-05-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0057_alter_vendor_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
