# Generated by Django 4.2.8 on 2024-05-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0059_alter_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='itassets.vendor'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='is_under_warranty',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Submitted to Vendor'), ('3', 'Completed')], default='1', max_length=20),
        ),
    ]
