# Generated by Django 4.2.8 on 2024-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0060_alter_maintenancerequest_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='Payment_Mode',
            field=models.CharField(choices=[('1', 'PO'), ('2', 'Cash')], max_length=20, null=True),
        ),
    ]
