# Generated by Django 4.2.8 on 2024-05-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0061_alter_maintenancerequest_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='it_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='itassets.it_prodcuts'),
        ),
    ]
