# Generated by Django 4.2.8 on 2024-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0063_maintenancerequest_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='Replaced_Device_Serial_Number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_Device_Repalced',
            field=models.BooleanField(null=True),
        ),
    ]
