# Generated by Django 4.2.8 on 2024-05-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0065_maintenancerequest_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maint_request_history',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Maint_Request_history', to='itassets.maintenancerequest'),
        ),
    ]
