# Generated by Django 4.2.8 on 2024-05-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0066_alter_maint_request_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maint_request_history',
            name='Request_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Maint_Request_history', to='itassets.maintenancerequest'),
        ),
        migrations.AlterField(
            model_name='maint_request_history',
            name='status',
            field=models.CharField(max_length=256),
        ),
    ]
