# Generated by Django 4.2.8 on 2024-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0067_maint_request_history_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maint_request_history',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
