# Generated by Django 4.2.8 on 2024-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0068_alter_maint_request_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maint_request_history',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
