# Generated by Django 4.2.8 on 2024-05-22 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0070_alter_it_prodcuts_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itassets/productimages'),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 22)),
        ),
        migrations.AlterField(
            model_name='it_prodcuts',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itassets.it_device_status'),
        ),
    ]
