# Generated by Django 4.2.8 on 2023-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0002_alter_expense_employee_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
