# Generated by Django 4.2.8 on 2024-01-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0006_expense_claimant_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='claimant',
            field=models.CharField(max_length=100),
        ),
    ]
