# Generated by Django 4.2.8 on 2024-01-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_checklistdetails_time'),
        ('pettycash', '0007_alter_expense_claimant'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='station_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.station'),
        ),
    ]
