# Generated by Django 4.2.8 on 2024-02-07 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0010_travelclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='upload_bill',
            field=models.FileField(blank=True, null=True, upload_to='travelclaimbills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
