# Generated by Django 4.2.8 on 2024-02-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0011_alter_travelclaim_upload_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='accommodation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='meals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='transportation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
