# Generated by Django 4.2.8 on 2024-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0013_remove_travelclaim_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
