# Generated by Django 4.2.8 on 2024-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0014_travelclaim_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
