# Generated by Django 4.2.8 on 2024-02-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0015_alter_travelclaim_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
