# Generated by Django 4.2.8 on 2024-02-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0016_travelclaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
