# Generated by Django 4.2.8 on 2024-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0017_alter_travelclaim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='approved_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
