# Generated by Django 4.2.8 on 2024-02-11 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0019_travelclaim_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 13, 38, 38, 242322, tzinfo=datetime.timezone.utc)),
        ),
    ]
