# Generated by Django 4.2.8 on 2024-02-12 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0020_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='approved_date',
            field=models.DateTimeField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 9, 15, 9, 617127, tzinfo=datetime.timezone.utc)),
        ),
    ]
