# Generated by Django 4.2.8 on 2024-02-12 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0022_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Approved_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 11, 42, 0, 655769, tzinfo=datetime.timezone.utc)),
        ),
    ]
