# Generated by Django 4.2.8 on 2024-02-12 18:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0023_expense_approved_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='upload_bill',
            field=models.FileField(blank=True, null=True, upload_to='PettycashInvoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 18, 2, 18, 659641, tzinfo=datetime.timezone.utc)),
        ),
    ]
