# Generated by Django 4.2.8 on 2024-02-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0024_expense_upload_bill_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 10, 22, 28, 616194, tzinfo=datetime.timezone.utc)),
        ),
    ]
