# Generated by Django 4.2.8 on 2024-02-16 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0028_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 34, 15, 480200, tzinfo=datetime.timezone.utc)),
        ),
    ]
