# Generated by Django 4.2.8 on 2024-02-16 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0030_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 23, 25, 9, 518773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 23, 25, 9, 520019, tzinfo=datetime.timezone.utc)),
        ),
    ]
