# Generated by Django 4.2.8 on 2024-02-17 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0032_alter_expense_date_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 9, 55, 43, 715159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 9, 55, 43, 716156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
