# Generated by Django 4.2.8 on 2024-02-17 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0033_alter_expense_date_alter_travelclaim_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 10, 1, 6, 818456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 10, 1, 6, 819492, tzinfo=datetime.timezone.utc)),
        ),
    ]
