# Generated by Django 4.2.8 on 2024-02-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0035_alter_expense_date_alter_travelclaim_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelclaim',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='travelclaim',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travelclaim',
            name='start_date',
        ),
    ]
