# Generated by Django 4.2.8 on 2024-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0036_remove_travelclaim_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
