# Generated by Django 4.2.8 on 2024-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0037_travelclaim_end_date_travelclaim_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
