# Generated by Django 4.2.8 on 2024-02-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_station_name'),
        ('pettycash', '0038_travelclaim_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
    ]
