# Generated by Django 4.2.8 on 2024-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0039_alter_expense_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelclaim',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
